# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2023-12-05 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('icon', models.CharField(default=None, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='nick name')),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('mail', models.CharField(max_length=64, unique=True)),
                ('avatar', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('title_id', models.IntegerField()),
            ],
        ),
    ]
